travis:
  secure:
    BINSTAR_TOKEN: nETS/h4J5lAKi/MVFOd/QWAzQSw0QSevUGQZpHjXpQJFmxbqkPFf2LI3JDFMvOw7pdG9M5phaOZJciemn4TFfyBHHM3hAh1QbzmVf9ec/lvV7IlKNn0TeDET7fzKUB+2tj1pCn0V1dG4f/1fHtCjlmRNZt65yla58ONytVY9dccrpDmqQqPGxeOHrkFiDWluoxFevWHJgv0XqP4uoBs8aj66Qks9auf5ojqysTx0W+cHB0Kth4ax4wO+LHyOvPvX098gOGQYIPTgWIaUtyuQfwkvPSk75vIRmK4XossCXKXdjpFAkfN2IUbhfwunlnIK5Qk7v3l17Ktnx9cqr/5JdN4lzN8rLx0zjZFnFsAKAuBizHeY+AoTaU5Wq5gbzbrfAY95WrhVJwvDk5DUt+UnAkyiEhkiLdwNGFNvL82lK0KXSOE9vPu7YFsqrN5ujxspQ8GNEkuZ7fHiIJu72/rhn2zWvo6vk5idlRF6MDOxkzGgxJLX7gEwsvnvVsri6he79T89IOVAiW6YEOquLv5y9Mf9po5OUnhNASql5IXSQvWJ3HLWLrRhWizfmrdPaHHnSlcGzqU21kgW9bTL4Vn9jtZHH2Ds1g37dNpAVMD0RsnxFlsi53JLqhEwY5VZYav77rD+BAe7rMZ3x8gtQkytSBXZWyKRH8jHF6kzLmysETo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
